name: CI

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        linux:
          - v5.10
          - v6.1
          - master
        cc:
          - gcc
        include:
          - linux: master
            cc: clang
    steps:
      - uses: actions/checkout@v3
        with:
          path: tp_smapi
      - uses: actions/checkout@v3
        with:
          repository: torvalds/linux
          ref: ${{ matrix.linux }}
          path: linux
      - run: sudo apt-get install -y libelf-dev ccache
      - uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.linux }}-${{ matrix.cc }}
      - run: make -C linux CC=${{ matrix.cc }} defconfig
      - name: Run make -C linux CC=${{ matrix.cc }}
        run: |
          export PATH="/usr/lib/ccache:$PATH"
          make -C linux -j $(nproc) CC=${{ matrix.cc }}
      - run: make -C tp_smapi modules KBUILD=../linux HDAPS=1 CC=${{ matrix.cc }}
